name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''
        with:
          fetch-depth: 0 # always fetch everything to be sure for codecov
      - uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          fetch-depth: 5 # because this is an manual trigger, only fetch the latest 5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load MongoDB binary cache
        id: cache-mongodb-binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/mongodb-binaries
          key: ${{ matrix.node-version }}
      - name: Install node_modules
        run: npm ci #yarn
#       - name: TSCheck
#         run: yarn --cwd packages/mongodb-memory-server-core run tscheck
      - name: ESLint
        run: npm run lint
      - name: Tests
        run: npm run test
#         run: yarn --cwd packages/mongodb-memory-server-core run coverage --colors
        env:
          CI: true

