# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create mongo Docker container
        id: build_mongo_docker

        uses: yog27ray/mongo-inmemory-action@v1.1.0
        with:
          image-version: latest
          port: 27017

      - name: Test mongo connection
        id: test_mongo_connection
        run: sudo mongo localhost:27017

      - uses: actions/checkout@v3

      - name: Clean Install
        run: npm ci

      - name: Run ESLint
        run: npm run lint 
        
      - name: run tests before building
        run: npm test

      - name: Build If possible
        run: npm run build --if-present

