name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#         work-dir: [server]
        node-version: [18.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v2.0.1
      
    - name: Clean Install npm packages
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint 

    - name: Run `npm test`
      run: npm test

      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017 # Access mongoDB Docker container
        




